------------------------------------------------------------
-- Core message engine schema (H2-friendly, Oracle-ish)
------------------------------------------------------------

CREATE TABLE MSG_COMPONENT_CONFIG (
  COMPONENT_ID    VARCHAR(64)   PRIMARY KEY,
  COMPONENT_NAME  VARCHAR(128)  NOT NULL,
  COMPONENT_TYPE  VARCHAR(64)   NOT NULL,
  CONFIG_SCOPE    VARCHAR(64)   DEFAULT 'GLOBAL',
  CONFIG_VERSION  INT           DEFAULT 1,
  CONFIG_STATE    VARCHAR(32)   DEFAULT 'ACTIVE',
  CONFIG_PAYLOAD  CLOB,
  DEPENDS_ON      VARCHAR(64),
  DESCRIPTION     VARCHAR(512),
  CREATED_BY      VARCHAR(64),
  CREATED_AT      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY      VARCHAR(64),
  UPDATED_AT      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX UQ_MSG_COMPONENT_NAME ON MSG_COMPONENT_CONFIG (COMPONENT_NAME);

------------------------------------------------------------
-- Component parameter overrides
------------------------------------------------------------

CREATE TABLE MSG_COMPONENT_PARAM (
  COMPONENT_ID    VARCHAR(64)   NOT NULL,
  PARAM_KEY       VARCHAR(128)  NOT NULL,
  PARAM_VALUE     VARCHAR(1024),
  VALUE_TYPE      VARCHAR(32)   DEFAULT 'STRING',
  OVERRIDE_SCOPE  VARCHAR(64)   DEFAULT 'DEFAULT',
  CREATED_BY      VARCHAR(64),
  CREATED_AT      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY      VARCHAR(64),
  UPDATED_AT      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (COMPONENT_ID, PARAM_KEY),
  CONSTRAINT FK_PARAM_COMPONENT
    FOREIGN KEY (COMPONENT_ID) REFERENCES MSG_COMPONENT_CONFIG(COMPONENT_ID)
);

------------------------------------------------------------
-- Component graph relations (pipelines, DLQ, error routes)
------------------------------------------------------------

CREATE TABLE MSG_COMPONENT_RELATION (
  RELATION_ID    VARCHAR(64)   PRIMARY KEY,
  PARENT_ID      VARCHAR(64)   NOT NULL,
  CHILD_ID       VARCHAR(64)   NOT NULL,
  RELATION_TYPE  VARCHAR(64)   NOT NULL,
  ORDER_INDEX    INT           DEFAULT 1,
  CREATED_BY     VARCHAR(64),
  CREATED_AT     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_REL_PARENT FOREIGN KEY (PARENT_ID)
    REFERENCES MSG_COMPONENT_CONFIG(COMPONENT_ID),
  CONSTRAINT FK_REL_CHILD FOREIGN KEY (CHILD_ID)
    REFERENCES MSG_COMPONENT_CONFIG(COMPONENT_ID)
);

------------------------------------------------------------
-- Event handler definitions (catalog of handlers)
------------------------------------------------------------

CREATE TABLE MSG_EVENT_HANDLER_DEF (
  HANDLER_ID      VARCHAR(64)   PRIMARY KEY,
  HANDLER_NAME    VARCHAR(128)  NOT NULL,
  HANDLER_TYPE    VARCHAR(64)   NOT NULL,
  IMPL_CLASS      VARCHAR(256)  NOT NULL,
  CONFIG_PAYLOAD  CLOB,
  DESCRIPTION     VARCHAR(512),
  CREATED_BY      VARCHAR(64),
  CREATED_AT      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY      VARCHAR(64),
  UPDATED_AT      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

------------------------------------------------------------
-- Logical handler chains
------------------------------------------------------------

CREATE TABLE MSG_HANDLER_CHAIN (
  CHAIN_ID      VARCHAR(64)   PRIMARY KEY,
  CHAIN_NAME    VARCHAR(128)  NOT NULL,
  CHAIN_SCOPE   VARCHAR(64)   DEFAULT 'GLOBAL',
  DESCRIPTION   VARCHAR(512),
  CREATED_BY    VARCHAR(64),
  CREATED_AT    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY    VARCHAR(64),
  UPDATED_AT    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX UQ_MSG_HANDLER_CHAIN_NAME ON MSG_HANDLER_CHAIN(CHAIN_NAME);

------------------------------------------------------------
-- Steps inside a handler chain (ordered)
------------------------------------------------------------

CREATE TABLE MSG_HANDLER_CHAIN_STEP (
  CHAIN_ID     VARCHAR(64)   NOT NULL,
  STEP_ORDER   INT           NOT NULL,
  HANDLER_ID   VARCHAR(64)   NOT NULL,
  STEP_CONFIG  CLOB,
  IS_ENABLED   CHAR(1)       DEFAULT 'Y',
  CREATED_BY   VARCHAR(64),
  CREATED_AT   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY   VARCHAR(64),
  UPDATED_AT   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (CHAIN_ID, STEP_ORDER),
  CONSTRAINT FK_CHAIN_STEP_CHAIN FOREIGN KEY (CHAIN_ID)
    REFERENCES MSG_HANDLER_CHAIN(CHAIN_ID),
  CONSTRAINT FK_CHAIN_STEP_HANDLER FOREIGN KEY (HANDLER_ID)
    REFERENCES MSG_EVENT_HANDLER_DEF(HANDLER_ID)
);

------------------------------------------------------------
-- Binding chains to components (per direction/phase)
------------------------------------------------------------

CREATE TABLE MSG_COMPONENT_CHAIN_BIND (
  BIND_ID       VARCHAR(64)   PRIMARY KEY,
  COMPONENT_ID  VARCHAR(64)   NOT NULL,
  CHAIN_ID      VARCHAR(64)   NOT NULL,
  DIRECTION     VARCHAR(16)   NOT NULL, -- INBOUND / OUTBOUND / BOTH
  PHASE         VARCHAR(16)   NOT NULL, -- PRE / POST / ERROR
  PRIORITY      INT           DEFAULT 1,
  IS_ENABLED    CHAR(1)       DEFAULT 'Y',
  CREATED_BY    VARCHAR(64),
  CREATED_AT    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY    VARCHAR(64),
  UPDATED_AT    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_BIND_COMPONENT FOREIGN KEY (COMPONENT_ID)
    REFERENCES MSG_COMPONENT_CONFIG(COMPONENT_ID),
  CONSTRAINT FK_BIND_CHAIN FOREIGN KEY (CHAIN_ID)
    REFERENCES MSG_HANDLER_CHAIN(CHAIN_ID)
);

------------------------------------------------------------
-- Audit table for component config changes
------------------------------------------------------------

CREATE TABLE MSG_COMPONENT_AUDIT (
  AUDIT_ID      BIGINT AUTO_INCREMENT PRIMARY KEY,
  COMPONENT_ID  VARCHAR(64)   NOT NULL,
  ACTION_TYPE   VARCHAR(32)   NOT NULL,
  OLD_PAYLOAD   CLOB,
  NEW_PAYLOAD   CLOB,
  CHANGED_BY    VARCHAR(64),
  CHANGED_AT    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  COMMENTS      VARCHAR(512),
  CONSTRAINT FK_AUDIT_COMPONENT FOREIGN KEY (COMPONENT_ID)
    REFERENCES MSG_COMPONENT_CONFIG(COMPONENT_ID)
);

------------------------------------------------------------
-- Minimal seed data for dev
------------------------------------------------------------

INSERT INTO MSG_COMPONENT_CONFIG (COMPONENT_ID, COMPONENT_NAME, COMPONENT_TYPE, CONFIG_STATE, CONFIG_PAYLOAD)
VALUES ('COMP_1', 'SampleInboundConsumer', 'INBOUND_CONSUMER', 'ACTIVE', '{"example":"payload"}');

INSERT INTO MSG_EVENT_HANDLER_DEF (HANDLER_ID, HANDLER_NAME, HANDLER_TYPE, IMPL_CLASS, DESCRIPTION)
VALUES ('H_LOG', 'LoggingHandler', 'LOGGING', 'com.yourorg.msgengine.handlers.LoggingHandler', 'Simple stdout logging handler');

INSERT INTO MSG_HANDLER_CHAIN (CHAIN_ID, CHAIN_NAME, DESCRIPTION)
VALUES ('CHAIN_IN_PRE', 'INBOUND_PRE_DEFAULT', 'Default inbound pre-processing chain');

INSERT INTO MSG_HANDLER_CHAIN_STEP (CHAIN_ID, STEP_ORDER, HANDLER_ID, IS_ENABLED)
VALUES ('CHAIN_IN_PRE', 1, 'H_LOG', 'Y');

INSERT INTO MSG_COMPONENT_CHAIN_BIND (BIND_ID, COMPONENT_ID, CHAIN_ID, DIRECTION, PHASE, IS_ENABLED)
VALUES ('BIND_1', 'COMP_1', 'CHAIN_IN_PRE', 'INBOUND', 'PRE', 'Y');
