spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCLCDB
    username: EXCEPTION_MGR
    password: EXCEPTION_MGR
    driver-class-name: oracle.jdbc.OracleDriver
  sql:
    init:
      mode: never
