-- ============================================================
-- H2 Schema for Workflow Engine (dev/test profiles)
-- Mirrors Oracle schema with H2-compatible syntax
-- ============================================================

-- Sequences
CREATE SEQUENCE IF NOT EXISTS WF_DEFINITION_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS WF_NODE_DEF_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS WF_TRANS_DEF_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS WF_INSTANCE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS WF_NODE_EXEC_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS WF_TRANS_LOG_SEQ START WITH 1 INCREMENT BY 1;

-- Workflow Definition
CREATE TABLE IF NOT EXISTS WF_DEFINITION (
    ID                BIGINT DEFAULT NEXT VALUE FOR WF_DEFINITION_SEQ PRIMARY KEY,
    NAME              VARCHAR(255) NOT NULL,
    DESCRIPTION       VARCHAR(1000),
    VERSION           INT NOT NULL,
    STATUS            VARCHAR(20) NOT NULL,
    RULES_ENGINE_TYPE VARCHAR(50),
    CREATED_AT        TIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_WF_DEF_NAME ON WF_DEFINITION(NAME);
CREATE INDEX IF NOT EXISTS IDX_WF_DEF_STATUS ON WF_DEFINITION(STATUS);

-- Node Definition
CREATE TABLE IF NOT EXISTS WF_NODE_DEFINITION (
    ID                      BIGINT DEFAULT NEXT VALUE FOR WF_NODE_DEF_SEQ PRIMARY KEY,
    WORKFLOW_DEFINITION_ID  BIGINT NOT NULL,
    NODE_KEY                VARCHAR(100) NOT NULL,
    NAME                    VARCHAR(255) NOT NULL,
    DESCRIPTION             VARCHAR(1000),
    NODE_TYPE               VARCHAR(20) NOT NULL,
    ACTION_HANDLER          VARCHAR(255),
    CONFIGURATION           VARCHAR(4000),
    TIMEOUT_SECONDS         BIGINT,
    MAX_RETRIES             INT,
    CONSTRAINT FK_NODE_DEF_WF FOREIGN KEY (WORKFLOW_DEFINITION_ID) REFERENCES WF_DEFINITION(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_NODE_DEF_WF ON WF_NODE_DEFINITION(WORKFLOW_DEFINITION_ID);

-- Transition Definition
CREATE TABLE IF NOT EXISTS WF_TRANSITION_DEFINITION (
    ID                      BIGINT DEFAULT NEXT VALUE FOR WF_TRANS_DEF_SEQ PRIMARY KEY,
    WORKFLOW_DEFINITION_ID  BIGINT NOT NULL,
    NAME                    VARCHAR(255),
    SOURCE_NODE_KEY         VARCHAR(100) NOT NULL,
    TARGET_NODE_KEY         VARCHAR(100) NOT NULL,
    CONDITION_EXPRESSION    VARCHAR(2000),
    PRIORITY                INT DEFAULT 0,
    CONSTRAINT FK_TRANS_DEF_WF FOREIGN KEY (WORKFLOW_DEFINITION_ID) REFERENCES WF_DEFINITION(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_TRANS_DEF_WF ON WF_TRANSITION_DEFINITION(WORKFLOW_DEFINITION_ID);
CREATE INDEX IF NOT EXISTS IDX_TRANS_DEF_SRC ON WF_TRANSITION_DEFINITION(WORKFLOW_DEFINITION_ID, SOURCE_NODE_KEY);

-- Workflow Instance
CREATE TABLE IF NOT EXISTS WF_INSTANCE (
    ID                      BIGINT DEFAULT NEXT VALUE FOR WF_INSTANCE_SEQ PRIMARY KEY,
    WORKFLOW_DEFINITION_ID  BIGINT NOT NULL,
    CORRELATION_ID          VARCHAR(255),
    STATUS                  VARCHAR(20) NOT NULL,
    CURRENT_NODE_KEY        VARCHAR(100),
    CONTEXT_DATA            VARCHAR(4000),
    CREATED_AT              TIMESTAMP NOT NULL,
    UPDATED_AT              TIMESTAMP,
    COMPLETED_AT            TIMESTAMP,
    CREATED_BY              VARCHAR(100),
    OPT_LOCK_VERSION        BIGINT DEFAULT 0,
    CONSTRAINT FK_INST_WF_DEF FOREIGN KEY (WORKFLOW_DEFINITION_ID) REFERENCES WF_DEFINITION(ID)
);

CREATE INDEX IF NOT EXISTS IDX_INST_WF_DEF ON WF_INSTANCE(WORKFLOW_DEFINITION_ID);
CREATE INDEX IF NOT EXISTS IDX_INST_STATUS ON WF_INSTANCE(STATUS);
CREATE INDEX IF NOT EXISTS IDX_INST_CORR_ID ON WF_INSTANCE(CORRELATION_ID);

-- Node Execution
CREATE TABLE IF NOT EXISTS WF_NODE_EXECUTION (
    ID                      BIGINT DEFAULT NEXT VALUE FOR WF_NODE_EXEC_SEQ PRIMARY KEY,
    WORKFLOW_INSTANCE_ID    BIGINT NOT NULL,
    NODE_DEFINITION_ID      BIGINT NOT NULL,
    NODE_KEY                VARCHAR(100) NOT NULL,
    STATUS                  VARCHAR(20) NOT NULL,
    INPUT_DATA              VARCHAR(4000),
    OUTPUT_DATA             VARCHAR(4000),
    ERROR_MESSAGE           VARCHAR(2000),
    RETRY_COUNT             INT DEFAULT 0,
    STARTED_AT              TIMESTAMP,
    COMPLETED_AT            TIMESTAMP,
    CONSTRAINT FK_NODE_EXEC_INST FOREIGN KEY (WORKFLOW_INSTANCE_ID) REFERENCES WF_INSTANCE(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_NODE_EXEC_INST ON WF_NODE_EXECUTION(WORKFLOW_INSTANCE_ID);
CREATE INDEX IF NOT EXISTS IDX_NODE_EXEC_STATUS ON WF_NODE_EXECUTION(WORKFLOW_INSTANCE_ID, STATUS);
CREATE INDEX IF NOT EXISTS IDX_NODE_EXEC_KEY ON WF_NODE_EXECUTION(WORKFLOW_INSTANCE_ID, NODE_KEY);

-- Transition Log (Audit Trail)
CREATE TABLE IF NOT EXISTS WF_TRANSITION_LOG (
    ID                        BIGINT DEFAULT NEXT VALUE FOR WF_TRANS_LOG_SEQ PRIMARY KEY,
    WORKFLOW_INSTANCE_ID      BIGINT NOT NULL,
    TRANSITION_DEFINITION_ID  BIGINT,
    FROM_NODE_KEY             VARCHAR(100) NOT NULL,
    TO_NODE_KEY               VARCHAR(100) NOT NULL,
    CONDITION_RESULT          VARCHAR(500),
    TRANSITIONED_AT           TIMESTAMP NOT NULL,
    CONSTRAINT FK_TRANS_LOG_INST FOREIGN KEY (WORKFLOW_INSTANCE_ID) REFERENCES WF_INSTANCE(ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_TRANS_LOG_INST ON WF_TRANSITION_LOG(WORKFLOW_INSTANCE_ID);
