-- ============================================================
-- Oracle Schema for Workflow Engine
-- ============================================================

-- Sequences
CREATE SEQUENCE WF_DEFINITION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE WF_NODE_DEF_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE WF_TRANS_DEF_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE WF_INSTANCE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE WF_NODE_EXEC_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE WF_TRANS_LOG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

-- Workflow Definition
CREATE TABLE WF_DEFINITION (
    ID                NUMBER(19) DEFAULT WF_DEFINITION_SEQ.NEXTVAL PRIMARY KEY,
    NAME              VARCHAR2(255) NOT NULL,
    DESCRIPTION       VARCHAR2(1000),
    VERSION           NUMBER(10) NOT NULL,
    STATUS            VARCHAR2(20) NOT NULL,
    CREATED_AT        TIMESTAMP NOT NULL,
    UPDATED_AT        TIMESTAMP,
    CONSTRAINT WF_DEF_STATUS_CHK CHECK (STATUS IN ('DRAFT', 'ACTIVE', 'DEPRECATED'))
);

CREATE INDEX IDX_WF_DEF_NAME ON WF_DEFINITION(NAME);
CREATE INDEX IDX_WF_DEF_STATUS ON WF_DEFINITION(STATUS);
CREATE UNIQUE INDEX UQ_WF_DEF_NAME_VER ON WF_DEFINITION(NAME, VERSION);

-- Node Definition
CREATE TABLE WF_NODE_DEFINITION (
    ID                      NUMBER(19) DEFAULT WF_NODE_DEF_SEQ.NEXTVAL PRIMARY KEY,
    WORKFLOW_DEFINITION_ID  NUMBER(19) NOT NULL,
    NODE_KEY                VARCHAR2(100) NOT NULL,
    NAME                    VARCHAR2(255) NOT NULL,
    DESCRIPTION             VARCHAR2(1000),
    NODE_TYPE               VARCHAR2(20) NOT NULL,
    ACTION_HANDLER          VARCHAR2(255),
    CONFIGURATION           VARCHAR2(4000),
    TIMEOUT_SECONDS         NUMBER(19),
    MAX_RETRIES             NUMBER(10),
    CONSTRAINT FK_NODE_DEF_WF FOREIGN KEY (WORKFLOW_DEFINITION_ID) REFERENCES WF_DEFINITION(ID) ON DELETE CASCADE,
    CONSTRAINT WF_NODE_TYPE_CHK CHECK (NODE_TYPE IN ('START', 'END', 'AUTO', 'WAIT_FOR_INPUT', 'FORK', 'JOIN'))
);

CREATE INDEX IDX_NODE_DEF_WF ON WF_NODE_DEFINITION(WORKFLOW_DEFINITION_ID);
CREATE UNIQUE INDEX UQ_NODE_DEF_KEY ON WF_NODE_DEFINITION(WORKFLOW_DEFINITION_ID, NODE_KEY);

-- Transition Definition
CREATE TABLE WF_TRANSITION_DEFINITION (
    ID                      NUMBER(19) DEFAULT WF_TRANS_DEF_SEQ.NEXTVAL PRIMARY KEY,
    WORKFLOW_DEFINITION_ID  NUMBER(19) NOT NULL,
    NAME                    VARCHAR2(255),
    SOURCE_NODE_KEY         VARCHAR2(100) NOT NULL,
    TARGET_NODE_KEY         VARCHAR2(100) NOT NULL,
    CONDITION_EXPRESSION    VARCHAR2(2000),
    PRIORITY                NUMBER(10) DEFAULT 0,
    CONSTRAINT FK_TRANS_DEF_WF FOREIGN KEY (WORKFLOW_DEFINITION_ID) REFERENCES WF_DEFINITION(ID) ON DELETE CASCADE
);

CREATE INDEX IDX_TRANS_DEF_WF ON WF_TRANSITION_DEFINITION(WORKFLOW_DEFINITION_ID);
CREATE INDEX IDX_TRANS_DEF_SRC ON WF_TRANSITION_DEFINITION(WORKFLOW_DEFINITION_ID, SOURCE_NODE_KEY);

-- Workflow Instance
CREATE TABLE WF_INSTANCE (
    ID                      NUMBER(19) DEFAULT WF_INSTANCE_SEQ.NEXTVAL PRIMARY KEY,
    WORKFLOW_DEFINITION_ID  NUMBER(19) NOT NULL,
    CORRELATION_ID          VARCHAR2(255),
    STATUS                  VARCHAR2(20) NOT NULL,
    CURRENT_NODE_KEY        VARCHAR2(100),
    CONTEXT_DATA            VARCHAR2(4000),
    CREATED_AT              TIMESTAMP NOT NULL,
    UPDATED_AT              TIMESTAMP,
    COMPLETED_AT            TIMESTAMP,
    CREATED_BY              VARCHAR2(100),
    OPT_LOCK_VERSION        NUMBER(19) DEFAULT 0,
    CONSTRAINT FK_INST_WF_DEF FOREIGN KEY (WORKFLOW_DEFINITION_ID) REFERENCES WF_DEFINITION(ID),
    CONSTRAINT WF_INST_STATUS_CHK CHECK (STATUS IN ('RUNNING', 'COMPLETED', 'FAILED', 'SUSPENDED', 'CANCELLED'))
);

CREATE INDEX IDX_INST_WF_DEF ON WF_INSTANCE(WORKFLOW_DEFINITION_ID);
CREATE INDEX IDX_INST_STATUS ON WF_INSTANCE(STATUS);
CREATE INDEX IDX_INST_CORR_ID ON WF_INSTANCE(CORRELATION_ID);

-- Node Execution
CREATE TABLE WF_NODE_EXECUTION (
    ID                      NUMBER(19) DEFAULT WF_NODE_EXEC_SEQ.NEXTVAL PRIMARY KEY,
    WORKFLOW_INSTANCE_ID    NUMBER(19) NOT NULL,
    NODE_DEFINITION_ID      NUMBER(19) NOT NULL,
    NODE_KEY                VARCHAR2(100) NOT NULL,
    STATUS                  VARCHAR2(20) NOT NULL,
    INPUT_DATA              VARCHAR2(4000),
    OUTPUT_DATA             VARCHAR2(4000),
    ERROR_MESSAGE           VARCHAR2(2000),
    RETRY_COUNT             NUMBER(10) DEFAULT 0,
    STARTED_AT              TIMESTAMP,
    COMPLETED_AT            TIMESTAMP,
    CONSTRAINT FK_NODE_EXEC_INST FOREIGN KEY (WORKFLOW_INSTANCE_ID) REFERENCES WF_INSTANCE(ID) ON DELETE CASCADE,
    CONSTRAINT WF_NODE_EXEC_STATUS_CHK CHECK (STATUS IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'WAITING_FOR_INPUT', 'SKIPPED'))
);

CREATE INDEX IDX_NODE_EXEC_INST ON WF_NODE_EXECUTION(WORKFLOW_INSTANCE_ID);
CREATE INDEX IDX_NODE_EXEC_STATUS ON WF_NODE_EXECUTION(WORKFLOW_INSTANCE_ID, STATUS);
CREATE INDEX IDX_NODE_EXEC_KEY ON WF_NODE_EXECUTION(WORKFLOW_INSTANCE_ID, NODE_KEY);

-- Transition Log (Audit Trail)
CREATE TABLE WF_TRANSITION_LOG (
    ID                        NUMBER(19) DEFAULT WF_TRANS_LOG_SEQ.NEXTVAL PRIMARY KEY,
    WORKFLOW_INSTANCE_ID      NUMBER(19) NOT NULL,
    TRANSITION_DEFINITION_ID  NUMBER(19),
    FROM_NODE_KEY             VARCHAR2(100) NOT NULL,
    TO_NODE_KEY               VARCHAR2(100) NOT NULL,
    CONDITION_RESULT          VARCHAR2(500),
    TRANSITIONED_AT           TIMESTAMP NOT NULL,
    CONSTRAINT FK_TRANS_LOG_INST FOREIGN KEY (WORKFLOW_INSTANCE_ID) REFERENCES WF_INSTANCE(ID) ON DELETE CASCADE
);

CREATE INDEX IDX_TRANS_LOG_INST ON WF_TRANSITION_LOG(WORKFLOW_INSTANCE_ID);
